import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:http/http.dart' as http;

class DiceBearImagePage extends StatefulWidget {
  @override
  _DiceBearImagePageState createState() => _DiceBearImagePageState();
}

class _DiceBearImagePageState extends State<DiceBearImagePage> {
  String imageUrl = '';

  // Method to fetch data from DiceBear API
  Future<void> fetchData() async {
    final url = Uri.parse('https://api.dicebear.com/7.x/adventurer/svg?seed=Felix');
    final response = await http.get(url);

    if (response.statusCode == 200) {
      setState(() {
        // Set the imageUrl to the fetched SVG content
        imageUrl = response.body;
      });
    } else {
      throw Exception('Failed to load image');
    }
  }

  @override
  void initState() {
    super.initState();
    fetchData(); // Fetch data when the page is initialized
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('DiceBear Image Page'),
      ),
      body: Center(
        child: imageUrl.isNotEmpty
            ? SingleChildScrollView(
                child: Column(
                  children: [
                    // Render the SVG image using the `flutter_svg` package
                    // Make sure to add the package to your pubspec.yaml file.
                    // Example: flutter_svg: ^0.24.0
                    SvgPicture.string(
                      imageUrl,
                      height: 200.0,
                    ),
                    SizedBox(height: 20.0),
                    Text('Image Generated by DiceBear API'),
                  ],
                ),
              )
            : CircularProgressIndicator(), // Show loading indicator while fetching data
      ),
    );
  }
}
